from pathlib import Path
import re
p=Path('stt.html')
s=p.read_text(encoding='utf-8')
for sid in ['ALLSTT-STT-FACE-GALLERY-FINAL','ALLSTT-STT-FACE-GALLERY-V7','ALLSTT-STT-RUNTIME-FIX-V5','ALLSTT-STT-FACE-GALLERY-V6','ALLSTT-STT-FACE-GALLERY-V5']:
    s=re.sub(r'<script[^>]*id=["\']'+re.escape(sid)+r'["\'][^>]*>.*?</script>','',s,flags=re.I|re.S)
s=s.replace('galleryAccessGranted ?','(galleryAccessGranted || window.allsttGalleryUnlocked) ?')
s=s.replace('if (galleryAccessGranted) {','if (galleryAccessGranted || window.allsttGalleryUnlocked) {')
s=s.replace('if (!galleryAccessGranted)','if (!(galleryAccessGranted || window.allsttGalleryUnlocked))')
s=s.replace('if(!galleryAccessGranted)','if(!(galleryAccessGranted || window.allsttGalleryUnlocked))')
patch='''<script id="ALLSTT-STT-FACE-GALLERY-FINAL">\n(function(){\nconst DOUBLE_TAP_MS=360;\nfunction getPw(){try{return typeof getGalleryPassword==="function"?getGalleryPassword():""}catch(_){return ""}}\nfunction unlock(){window.allsttGalleryUnlocked=true;try{renderAreas()}catch(_){}try{updateAreaSelector()}catch(_) {}}\nfunction install(){\nconst face=document.getElementById("takeOfficerPhotoBtn"),cam=document.getElementById("officerPhotoInput"),gal=document.getElementById("officerGalleryInput"),section=document.getElementById("officerSection");\nif(!face||!cam||!gal||!section||face.dataset.faceFinal==="1")return;\ngal.style.display="none";gal.removeAttribute("capture");\nconst old=document.getElementById("uploadOfficerGalleryBtn");if(old)old.remove();\nconst btn=face.cloneNode(true);btn.dataset.faceFinal="1";face.replaceWith(btn);\nlet waiting=false,timer=null;function clear(){waiting=false;if(timer){clearTimeout(timer);timer=null}}\nfunction camera(){clear();cam.value="";cam.setAttribute("accept","image/*");cam.setAttribute("capture","user");cam.click()}\nfunction gate(){clear();const entered=window.prompt("Masukkan password untuk membuka Upload Foto dari Galeri:");if(entered===null)return;if(entered!==getPw()){window.alert("Password salah. Akses galeri ditolak.");return}unlock();let g=document.getElementById("uploadOfficerGalleryBtn");if(!g){g=document.createElement("button");g.id="uploadOfficerGalleryBtn";g.type="button";g.className="btn btn-ghost";g.textContent="UPLOAD FOTO DARI GALERI";g.style.cssText="display:inline-flex;margin-top:10px;font-weight:800";section.appendChild(g)}g.onclick=()=>{gal.value="";gal.click()};window.alert("Password benar. Upload Foto dari Galeri sudah terbuka.")}\nbtn.addEventListener("click",e=>{e.preventDefault();e.stopPropagation();e.stopImmediatePropagation();if(waiting){gate();return}waiting=true;timer=setTimeout(()=>{if(waiting)camera()},DOUBLE_TAP_MS)},true);\ngal.addEventListener("change",()=>{const f=gal.files&&gal.files[0];if(!f)return;try{const dt=new DataTransfer();dt.items.add(f);cam.files=dt.files;cam.dispatchEvent(new Event("change",{bubbles:true}))}catch(e){window.alert("Gagal meneruskan foto galeri: "+e.message)}finally{gal.value=""}},true);\n}\nif(document.readyState==="loading")document.addEventListener("DOMContentLoaded",install,{once:true});else install();window.addEventListener("load",install);[300,800,1500,2500].forEach(ms=>setTimeout(install,ms));\n})();\n</script>'''
s=s.replace('</body>',patch+'\n</body>',1)
p.write_text(s,encoding='utf-8')