from pathlib import Path
import re

p=Path('stt.html')
s=p.read_text(encoding='utf-8')
marker='<!-- ALLSTT_COMPANY_IDENTITY_V1 -->'
if marker in s:
    raise SystemExit('identity patch already present')

css='''\n<style id="allstt-company-identity-css">\n.company-identity-settings{background:#fff;border-radius:18px;padding:20px;margin:20px 0;box-shadow:0 6px 18px rgba(15,23,36,.12)}\n.company-identity-settings h3{margin:0 0 14px;color:#0b3d91}\n.company-identity-settings .identity-grid{display:grid;grid-template-columns:1fr 1fr;gap:14px}\n.company-identity-settings input{width:100%;padding:12px;border:2px solid #e2e8f0;border-radius:10px}\n.company-identity-settings .identity-actions{display:flex;gap:10px;flex-wrap:wrap;margin-top:14px}\n.company-identity-settings img{width:64px;height:64px;object-fit:contain;border:1px solid #ddd;border-radius:8px;background:#fff}\n@media(max-width:700px){.company-identity-settings .identity-grid{grid-template-columns:1fr}}\n</style>\n'''
js='''\n<!-- ALLSTT_COMPANY_IDENTITY_V1 -->\n<script>\n(function(){\n const KEY='ALLSTT_GLOBAL_COMPANY_IDENTITY_V1';\n const DEFAULT={name:'',address:'',leftLogo:'',rightLogo:''};\n function load(){try{return Object.assign({},DEFAULT,JSON.parse(localStorage.getItem(KEY)||'{}'))}catch(e){return {...DEFAULT}}}\n function save(v){localStorage.setItem(KEY,JSON.stringify(v));apply(v)}\n function apply(v){\n   document.querySelectorAll('[data-company-name],#companyName,.company-name').forEach(e=>{if('value' in e)e.value=v.name;e.textContent=v.name});\n   document.querySelectorAll('[data-company-address],#companyAddress,.company-address').forEach(e=>{if('value' in e)e.value=v.address;e.textContent=v.address});\n   const imgs=document.querySelectorAll('[data-company-logo-left],#companyLogoLeft,.company-logo-left'); if(imgs.length&&v.leftLogo) imgs.forEach(e=>e.src=v.leftLogo);\n   const imgs2=document.querySelectorAll('[data-company-logo-right],#companyLogoRight,.company-logo-right'); if(imgs2.length&&v.rightLogo) imgs2.forEach(e=>e.src=v.rightLogo);\n   window.ALLSTT_COMPANY_IDENTITY=v;\n }\n function reader(file,cb){if(!file)return;const r=new FileReader();r.onload=()=>cb(r.result);r.readAsDataURL(file)}\n function panel(){\n   if(document.getElementById('allsttCompanyIdentityPanel'))return;\n   const host=document.querySelector('.container')||document.body;\n   const box=document.createElement('section');box.id='allsttCompanyIdentityPanel';box.className='company-identity-settings';\n   box.innerHTML=`<h3>Pengaturan Identitas Perusahaan</h3><div class="identity-grid"><div><label>Nama Perusahaan</label><input id="ciName" type="text"></div><div><label>Alamat Perusahaan</label><input id="ciAddress" type="text"></div><div><label>Logo Kiri</label><input id="ciLeft" type="file" accept="image/*"><img id="ciLeftPreview"></div><div><label>Logo Kanan</label><input id="ciRight" type="file" accept="image/*"><img id="ciRightPreview"></div></div><div class="identity-actions"><button class="btn btn-primary" id="ciSave">Simpan Identitas</button><button class="btn btn-ghost" id="ciReset">Reset Default</button></div>`;\n   host.insertBefore(box,host.firstChild);\n   const v=load();ciName.value=v.name;ciAddress.value=v.address;ciLeftPreview.src=v.leftLogo||'';ciRightPreview.src=v.rightLogo||'';\n   ciLeft.onchange=e=>reader(e.target.files[0],x=>ciLeftPreview.src=x);ciRight.onchange=e=>reader(e.target.files[0],x=>ciRightPreview.src=x);\n   ciSave.onclick=()=>save({name:ciName.value.trim(),address:ciAddress.value.trim(),leftLogo:ciLeftPreview.src||'',rightLogo:ciRightPreview.src||''});\n   ciReset.onclick=()=>{localStorage.removeItem(KEY);const d=load();ciName.value=d.name;ciAddress.value=d.address;ciLeftPreview.src='';ciRightPreview.src='';apply(d)};\n }\n document.addEventListener('DOMContentLoaded',()=>{panel();apply(load())});\n})();\n</script>\n'''
# Insert CSS before </head> and UI script after it, without touching existing features.
s=s.replace('</head>',css+'</head>',1)
s=s.replace('</body>',js+'</body>',1)
p.write_text(s,encoding='utf-8')
print('patched',p)
